### ISSUE TITLE
Restore database Moor flutter

### ISSUE THREAD

**Issue by DougSiqueira** [simolus3/drift#376]
How to generate backup file and restore the file on another device?

**Comment by simolus3** [comment]
Moor databases are just regular files on the device, so you can pull them like any other file.

If you tell me from which device you want to extract the database (Android / iOS) and how you're using `FlutterQueryExecutor`/ `VmDatabase`, I can help finding the exact file location.

**Comment by DougSiqueira** [comment]
Currently Android only.
FlutterQueryExecutor
  path: 'dbnew.sqlite'
example my db [moor flutter](https://github.com/DougSiqueira/Test-Moor-Flutter-/blob/master/lib/moor_database/moor_database.dart)



I am looking to develop two buttons in the application. A button so that users can export the data generating the backup and can send it to another device.
And another button for you to import and restore data.

**Comment by simolus3** [comment]
If you need to do it programmatically, you can locate the database file like this:
```dart
import 'package:path/path.dart' as p;
import 'package:sqflite/sqflite.dart';

final dbFolder = await getDatabasesPath();
final dbLocation = p.join(dbFolder, 'dbnew.sqlite');
```

Now, you can use `File(dbLocation).readAsBytes()` to obtain the raw database bytes. To store the data, you can use `File(dbLocation).writeAsBytes(updatedContent)`. Reads should be harmless, but you should `close` the moor database before writing, then open it again when the write was completed.

Security notice: You should be careful when allowing users to store abitrary sqlite files. It was possible to craft malicious database files that can [leak your apps memory](https://research.checkpoint.com/2019/select-code_execution-from-using-sqlite/). This bug has been fixed in sqlite, but Android devices commonly use an old sqlite version.

**Comment by DougSiqueira** [comment]
Thanks. I am able to backup and send dbnew.sqlite.

```
   Future <void> backupp () async {
     final dbFolder = await getDatabasesPath ();
     final dbLocation = p.join (dbFolder, 'dbnew.sqlite');
     final File file = File (dbLocation);
     await ShareExtend.share (file.path, "file");
   }
```

But I'm still not able to access the received file and restore it "on another device".

Can you give me an example?

**Comment by simolus3** [comment]
I don't know how you want to receive the backup file (file chooser, intent handling, ...). This is unrelated to moor, searching for something like "flutter receive file" might lead to something you need.

If you have a `ByteData` or `Uint8List`, you can just store that into the target file.

**Comment by DougSiqueira** [comment]
I'm doing this, but I'm not restoring the data.

```
Asynchronous <void> restore () future {
final dbFolder = wait for getDatabasesPath ();
final dbLocation = p.join (dbFolder, 'dbnew.sqlite');

// backup the access file
File file = wait for FilePicker.getFile (type: FileType.ANY);
final db = AppDatabase ();
db.close ();
Uint8List updatedContent = wait for File (file.path) .readAsBytes ();
print (updatedContent);
File (dbLocation) .writeAsBytes (updatedContent);
}
```

**Comment by Pepper20** [comment]
> Moor databases are just regular files on the device, so you can pull them like any other file.
> 
> If you tell me from which device you want to extract the database (Android / iOS) and how you're using `FlutterQueryExecutor`/ `VmDatabase`, I can help finding the exact file location.

@simolus3 thanks for your lib. But I need your help.

I'm also trying to develop for my application the function of local in device backup for users uninstal and reinstall it recovering the old data. In my case, it'll be a local backup, so it's not for sharing the data with another device. It's just to backup and restore  internally in the device.


It's for the Android system
File Name: storesdb.sqlite
I'm using: moor_flutter: ^ 2.1.0

**Comment by simolus3** [comment]
> but I'm not restoring the data

@DougSiqueira could it be that there is another database instance of `AppDatabase` open at the same time? You would have to close all of them.

@Pepper20 The same approach should work, you just need to exchange the file name.

**Comment by Pepper20** [comment]
> > but I'm not restoring the data
> 
> @DougSiqueira could it be that there is another database instance of `AppDatabase` open at the same time? You would have to close all of them.
> 
> @Pepper20 The same approach should work, you just need to exchange the file name.

I couldn't do it, I'm a beginner. Can you please give me an example without sharing file, I need generate and restore backup in device.

**Comment by DougSiqueira** [comment]
> > but I'm not restoring the data
> 
> @DougSiqueira could it be that there is another database instance of `AppDatabase` open at the same time? You would have to close all of them.

I updated my code leaving only a single instance of the database. But it's still not working.

But I did a test with a device with Android 7.1.1. That landed root. And restored.

Can I only restore the database if the device is rooted?

**Comment by DougSiqueira** [comment]
@Pepper20 

Test this, without sharing a file, just saving it to a variable and restoring it.
The problem is that it only worked here on a rooted device.
  
` Uint8List testBackup;
`

```

  Future<void> backup() async {
    DataProvaider dataProvaider =
        Provider.of<DataProvaider>(context, listen: false);

    final dbFolder = await getDatabasesPath();
    final dbLocation = p.join(dbFolder, 'dbnew.sqlite');

    final File file = File(dbLocation);
    dataProvaider.testBackup = await File(file.path).readAsBytes();
    print(dataProvaider.testeBackup);
  }
```

```

  Future<void> restore() async {
    DataProvaider dataProvaider =
        Provider.of<DataProvaider>(context, listen: false);

    final dbFolder = await getDatabasesPath();
    final dbLocation = p.join(dbFolder, 'dbnew.sqlite');

    AppDatabase.instance.close();
    await File(dbLocation).writeAsBytes(dataProvaider.testBackup);

  }


```

**Comment by ShehanMadushanka** [comment]
I think the best way is write all the data to a csv file.

**Comment by DougSiqueira** [comment]
@simolus3, I found out it’s working.
The problem is that the restore functionality is not working on some devices.

it didn't work on: Motorola one zoom / with android 9, redminote 7 / with android 9, redminote 8 / with android 9.

it worked on: Samsung Galaxy S9 / with Android 9, Moto G 5S with Android 7.1, Samsung on7 with Android 6.0, Redmi 4x / with Android 7.1.


```
Future<void> restore() async {

    final dbFolder = await getDatabasesPath();
    final dbLocation = p.join(dbFolder, 'dbnew.sqlite');
    AppDatabase.instance.close(); 

    //acess file backup
    File file = await FilePicker.getFile(type: FileType.ANY);
    Uint8List updatedContent = await File(file.path).readAsBytes();
    File(dbLocation).writeAsBytes(updatedContent);
  }
```
Permissions in `AndroidManifest.xml`


```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.USE_FINGERPRINT"/>
```

Do you have any idea of the reason for this bug, or a suggestion on how to resolve it?

**Comment by simolus3** [comment]
Thanks for the additional information!

I don't know anything obvious that could cause this unfortunately. Can you try using `moor_ffi` and see if that solves the problem? With `moor_ffi` we ship our own version of libsqlite3.so to android devices, which should fix differences between devices. The migration should be a [simple change](https://moor.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor-flutter-to-moor-ffi).

**Comment by DougSiqueira** [comment]
@simolus3 Thank you, I think this is really the way.  I migrated for `moor_ffi`. But it is giving  a bug. I think it's because is just closing "`AppDatabase.instance.close()`"  and it's not reopening in the end.
How can I then open it again the data base, when the write was completed.

**Comment by simolus3** [comment]
After you call `AppDatabase.close`, that instance is gone forever and shouldn't be re-opened. You could create a new `AppDatabase` and open that, though.

**Comment by davidmartos96** [comment]
@DougSiqueira Maybe it's failing in some devices because you are not awaiting the database close in the restore method. Also, I would pass the flag `flush` to `true` when writing the bytes as well.

**Comment by DougSiqueira** [comment]
@simolus3 
After I switched to moor_ffi, I started having problems with database corruption. Often just installing the apk.
Can you tell me what may be causing this?


```
class AppDatabase extends _$AppDatabase {
  static AppDatabase instance = AppDatabase._internal();

  AreaTypeDao areaTypeDao;
  ClassRCDDao classRCDDao;
  DiscardRecordDao discardRecordDao;
  TypeMaterialDao typeMaterialDao;

  AppDatabase._internal()
      : super(LazyDatabase(() async {
          final dbFolder = await getDatabasesPath();
          final file = File(p.join(dbFolder, 'vigiaEntulho.sqlite'));
          return VmDatabase(file);
        })) {
    areaTypeDao = AreaTypeDao(this);
    classRCDDao = ClassRCDDao(this);
    discardRecordDao = DiscardRecordDao(this);
    typeMaterialDao = TypeMaterialDao(this);
  }
.....
```

**Comment by DougSiqueira** [comment]
> @DougSiqueira Maybe it's failing in some devices because you are not awaiting neither the database close or the bytes writing in the restore method. Also, I would pass the flag `flush` to `true` when writing the bytes as well.
> 
> ```dart
> Future<void> restore() async {
>     final dbFolder = await getDatabasesPath();
>     final dbLocation = p.join(dbFolder, 'dbnew.sqlite');
>     await AppDatabase.instance.close(); 
> 
>     //acess file backup
>     File file = await FilePicker.getFile(type: FileType.ANY);
>     Uint8List updatedContent = await File(file.path).readAsBytes();
>     await File(dbLocation).writeAsBytes(updatedContent, flush: true);
> }
> ```
> 
> I don't see why it would have to behave different using `moor_ffi` or `moor_flutter` in this case.


Thanks! But I had tested it, and it didn't work for the devices mentioned. Really what made it work on devices that were not working was to migrate to moor_ffi. But unfortunately it is causing me other problems with the database.

**Comment by DougSiqueira** [comment]
@simolus3 
After I switched to moor_ffi, I started having problems with database corruption. Often just installing the apk.
Can you tell me what may be causing this?


```
class AppDatabase extends _$AppDatabase {
  static AppDatabase instance = AppDatabase._internal();

  AreaTypeDao areaTypeDao;
  ClassRCDDao classRCDDao;
  DiscardRecordDao discardRecordDao;
  TypeMaterialDao typeMaterialDao;

  AppDatabase._internal()
      : super(LazyDatabase(() async {
          final dbFolder = await getApplicationDocumentsDirectory();
          final file = File(p.join(dbFolder.path, 'db.sqlite'));
          return VmDatabase(file);
        })) {
    areaTypeDao = AreaTypeDao(this);
    classRCDDao = ClassRCDDao(this);
    discardRecordDao = DiscardRecordDao(this);
    typeMaterialDao = TypeMaterialDao(this);
  }
.....
```

**Comment by simolus3** [comment]
Hm, that code looks alright to me. What kind of "database corruption" issues are you seeing?

**Comment by DougSiqueira** [comment]
I think that's when I try to create a new AppDatabase, after restoring the database.
What I was able to do to resolve it was to close the application, `SystemNavigator.pop();`  so that the user can open it again.
How can I improve this?

```
Future<void> restore() async {
  final dbFolder = await getApplicationDocumentsDirectory();
  final dbLocation = p.join(dbFolder.path, 'db.sqlite');

  await AppDatabase.instance.close();
  //acess file backup
  String file = (await FilePicker.getFilePath(fileExtension: ".sqlite"));

  Uint8List updatedContent = await File(file).readAsBytes();

  await File(dbLocation).writeAsBytes(updatedContent, flush: true);
  //for start database
  SystemNavigator.pop();
}


```

**Comment by simolus3** [comment]
I've added an [integration test](https://github.com/simolus3/moor/blob/develop/extras/integration_tests/vm/test/save_and_restore_test.dart) to replay this use case. In there, we close the database, swap the underlying file, then re-open. That should be very similar to what you're doing, right?

**Comment by arpit-d** [comment]
@DougSiqueira did you ever get it to work properly? Curious, since I'm planning to add backup/restore functionality in my app as well!

**Comment by richard457** [comment]
> If you need to do it programmatically, you can locate the database file like this:
> 
> ```dart
> import 'package:path/path.dart' as p;
> import 'package:sqflite/sqflite.dart';
> 
> final dbFolder = await getDatabasesPath();
> final dbLocation = p.join(dbFolder, 'dbnew.sqlite');
> ```
> 
> Now, you can use `File(dbLocation).readAsBytes()` to obtain the raw database bytes. To store the data, you can use `File(dbLocation).writeAsBytes(updatedContent)`. Reads should be harmless, but you should `close` the moor database before writing, then open it again when the write was completed.
> 
> Security notice: You should be careful when allowing users to store abitrary sqlite files. It was possible to craft malicious database files that can [leak your apps memory](https://research.checkpoint.com/2019/select-code_execution-from-using-sqlite/). This bug has been fixed in sqlite, but Android devices commonly use an old sqlite version.

Does this code work on android 10? according to this https://developer.android.com/about/versions/10/behavior-changes-10 I guess but not sure that with android 10 you can not exec on app home directory correct me if I am wrong.

**Comment by simolus3** [comment]
> you can not exec on app home directory

Database files aren't executed, they just store data.

If your comment refers to the security notice, that still applies. While database files don't contain executable machine code, sqlite3 will interpret what's contained in them, even if the files can't be executed.

**Comment by JoDehli** [comment]
Hey everbody,
I also have a problem with exporting the database. I have written a small app to store meter readings. The app runs without problems. Also the export of the database works fine. But as soon as I did the export the UI will not be updated anymore. 

I can enter and delete data but the changes are not updated in the UI but after a complete restart of the app the changes are there. 

Here is the code for the main.dart
```dart  void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final db = AppDatabase.instance;
  @override
  void dispose() {
    db.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        Provider(create: (_) => db.zaehler),
        Provider(create: (_) => db.entry)
      ],
      child: MaterialApp(
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: [
          //const Locale('en'), // English§
          const Locale('de'), // de
        ],
        debugShowCheckedModeBanner: false,
        initialRoute: '/',
        onGenerateRoute: Router.generateRoute,
        title: 'Zäehlerstände',
        theme: ThemeData(
          brightness: Brightness.light,
          primaryColor: Colors.lightBlue,
          accentColor: Colors.lightBlue,
        ),
        home: MyStartPage(title: 'Zählerstände'),
      ),
    );
  }
}`
```

And here is the backup Function:

```dart
  Future<void> _backup() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));

    final Directory exportDir = await getSafeDir();
    final fileBackup = File(p.join(exportDir.path, 'db_backup.sqlite'));

    var db = AppDatabase.instance;
    await db.close();
    if (await fileBackup.exists()) {
      await fileBackup.delete();
    }

    await fileBackup.writeAsBytes(await file.readAsBytes(), flush: true);

    if (await fileBackup.exists()) {
      bool res = await FlutterShare.shareFile(
        title: "db_backup.sqlite",
        text: "Backup Sql",
        filePath: fileBackup.path,
      );
        db = AppDatabase.executor(VmDatabase(file));
        Navigator.popUntil(
            context, ModalRoute.withName(Navigator.defaultRouteName));
      
    } else {
      print("File not Found");
    }
  }
```

And here is the page where I pop back from the backup function: 

```dart
class MyStartPage extends StatefulWidget {
  final String title;

  MyStartPage({Key key, this.title});

  @override
  _MyStartPageState createState() => _MyStartPageState();
}

class _MyStartPageState extends State<MyStartPage> {
  @override
  Widget build(BuildContext context) {
    Color color = Theme.of(context).primaryColor;

    return Scaffold(
      appBar: startPageAppBars(context, this.widget.title),
      body: Center(child: _buildTaskList(context)),
      bottomNavigationBar: StartPageBottomAppBar(color: color.value),
      floatingActionButton: FloatingActionButton(
        key: const Key('add_zaehler'),
        tooltip: "Neuer Zähler",
        child: const Icon(Icons.add),
        onPressed: () {
          displayAddZaehlerDialog(context, -1);
        },
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
    );
  }
}

Widget _top(String name, DateTime lastEntry) {
  final double w = 75;
  String _name;
  String _dateAsString = "-";
  if (name != null) {
    _name = name;
  }

  if (lastEntry != null) {
    _dateAsString = normalDate(lastEntry).toString();
  }

  return Padding(
    padding: const EdgeInsets.all(8.0),
    child: Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: <Widget>[
        SizedBox(
          width: w,
          child: Text(
            "",
            style: TextStyle(fontSize: 14),
          ),
        ),
        Text(
          _name,
          style: TextStyle(fontSize: 26),
        ),
        SizedBox(
          width: w,
          child: Text(
            _dateAsString,
            style: TextStyle(fontSize: 14),
          ),
        ),
      ],
    ),
  );
}

StreamBuilder<List<CounterData>> _buildTaskList(BuildContext context) {
  final dao = Provider.of<ZaehlerDao>(context);
  final dao2 = Provider.of<EntryDao>(context);

  return StreamBuilder(
    stream: dao.watchAllZaehler(),
    builder: (context, AsyncSnapshot<List<CounterData>> snapshot) {
      final counters = snapshot.data ?? List();

      return ListView.builder(
        itemCount: counters.length,
        itemBuilder: (_, index) {
          final entityCounter = counters[index];

          return Slidable(
              actionPane: SlidableDrawerActionPane(),
              secondaryActions: <Widget>[
                Card(
                  child: IconSlideAction(
                    caption: 'Löschen',
                    color: Color(entityCounter.colorValue),
                    icon: Icons.delete,
                    onTap: () {
                      dao
                          .deleteCounter(entityCounter)
                          .then((_) => dao2.deleteZaehler(entityCounter.id));
                    },
                  ),
                )
              ],
              child: InkWell(
                key: Key(entityCounter.name),
                onLongPress: () {
                  displayAddZaehlerDialog(context, entityCounter.id);
                },
                onTap: () async {
                  List<int> jahre =
                      await dao2.getAllYearsById(entityCounter.id);

                  final ZaehlerEntryArgs args = ZaehlerEntryArgs(
                      entityCounter.name,
                      entityCounter.id,
                      entityCounter.colorValue,
                      getYearFromDate(DateTime.now()),
                      jahre,
                      entityCounter.einheit);
                  Navigator.pushNamed(context, '/get_zaehler_entries',
                      arguments: args);
                },
                child: Card(
                  elevation: 8,
                  color: Color(entityCounter.colorValue),
                  child: Container(
                      height: 90,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: <Widget>[
                          _top(entityCounter.name, entityCounter.lastEntry),
                          Expanded(
                              child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: <Widget>[
                              Text(
                                entityCounter.currenValue.toString() +
                                    " " +
                                    entityCounter.einheit.toString(),
                                style: TextStyle(
                                    fontSize: 18, fontWeight: FontWeight.bold),
                              ),
                            ],
                          )),
                        ],
                      )),
                ),
              ));
        },
      );
    },
  );
}
```

The complete database file is here in the zip file:
[moor_database.dart.zip](https://github.com/simolus3/moor/files/5151918/moor_database.dart.zip)

I am relatively new to the Flutter world. Probably there is a fatal error in the handling of the provider package and moor. 

Can someone help me with this problem? 

Thanks in advance.
Jojo

**Comment by simolus3** [comment]
@JoDehli One thing that comes to mind is that, in `_backup`, you're effectively closing `AppDatabase.instance`, but then you never really re-open it. Where you set `db = AppDatabase(VmDatabase(file))`, you probably meant to set `AppDatabase.instance = ...`.

Even if you did set `AppDatabase.instance`, your widget would still reference the old database instance since it stores it in a field too. A simple way to fix this is to wrap the instance in a [`ValueNotifier`](https://api.flutter.dev/flutter/foundation/ValueNotifier-class.html) that you can listen to. The widget could `setState` when the database changes to continue providing the right streams.

**Comment by JoDehli** [comment]
@simolus3 Thanks for your reply. I will try it this weekend. I let you know if I could solve it. If I can not get it to work I will export da database via json or other text fromat. But I hate it when I have to give up on a programming problem :-)

**Comment by JoDehli** [comment]
@simolus3 I tried it but I did not get it to work. I have started a last attempt by creating a simple project. Could you take a look at it? It has only 2 screens. 

The project can be found under: 

https://github.com/JoDehli/FlutterMoorDatabaseBackupAndResore

I think it is a very easy task for you. 

Thanks very much in advance.

**Comment by simolus3** [comment]
I added a very simple `ChangeNotifier` to re-open the database. Run `git apply` [fix_backups.txt](https://github.com/simolus3/moor/files/5178368/fix_backups.txt) to use it.

**Comment by JoDehli** [comment]
@simolus3 Great! Thank you very munch!!! Works perfectly. Will try it in my counter app. 
I integrated it in the https://github.com/JoDehli/FlutterMoorDatabaseBackupAndResore example. Maybe it is helpful 
for others too.

**Comment by rajumb502** [comment]
Hello All
I was trying to create and package a sqlite DB along with my app. I checked in the .apk file that the db file exists. When I try to copy the database and use it for my app, I get an error: 

> Failed to load dynamic library (dlopen failed: library \"/data/data/com.example.moor_bloc/lib/libsqlite3.so\" not found).

 This module was working fine when I was importing the data from an XML file. I have used the pointer from https://moor.simonbinder.eu/docs/examples/existing_databases/
```
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getDatabasesPath(); 
    final file = File(p.join(dbFolder, 'app.db'));

    if (!await file.exists()) {
      // Extract the pre-populated database file from assets
      final ByteData data = await rootBundle.load('assets/books.db');
      await file.writeAsBytes(data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes), flush: true);
    }

    return VmDatabase(file);
  });
}

```

I have tried the suggesting in this thread but I keep getting stuck with this exception. Any ideas on how to resolve this?

Below are the packages I am importing:
```
import 'package:moor_flutter/moor_flutter.dart';
import 'package:sqflite/sqflite.dart';
import 'package:path/path.dart' as p;
import 'dart:io';
import 'package:moor/moor.dart';
import 'package:moor/ffi.dart';
import 'package:flutter/services.dart' show ByteData, rootBundle;
import 'package:moor_bloc/src/file_helper.dart'; //for parsing XML file

```

**Comment by simolus3** [comment]
It looks like you were already using `moor_flutter`? You can just continue to use a `FlutterQueryExecutor`, you don't need a `VmDatabase` for this I think. If you want to use `moo/ffi`, you also need a dependency on `sqlite3_flutter_libs`.

**Comment by rajumb502** [comment]
Thank you very much @simolus3 . Worked like a charm :) For future reference, this is how the code looks like now:

```
//ref: https://moor.simonbinder.eu/docs/examples/existing_databases/
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getDatabasesPath();
    final file = File(p.join(dbFolder, 'app.db'));

    if (!await file.exists()) {
      // Extract the pre-populated database file from assets
      final ByteData data = await rootBundle.load('assets/books.db');
      await file.writeAsBytes(data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes), flush: true);
    }

    return FlutterQueryExecutor.inDatabaseFolder(path: file.path); 
  });
}
```

Imports:
```
import 'dart:io';
import 'package:moor_flutter/moor_flutter.dart';
import 'package:flutter/services.dart' show ByteData, rootBundle;
import 'package:sqflite/sqflite.dart'; //for getDatabasesPath
import 'package:path/path.dart' as p;

```

**Comment by ngxingyu** [comment]
Just wondering, is it possible to restore the database (either from a file in assets or downloaded from some online storage) when using WebDatabase?

**Comment by simolus3** [comment]
@ngxingyu The `WebDatabase` has an `initializer` parameter that can be used to load the database bytes when no database has been stored locally. Is that what you need?

**Comment by ngxingyu** [comment]
> @ngxingyu The `WebDatabase` has an `initializer` parameter that can be used to load the database bytes when no database has been stored locally. Is that what you need?

Oh yes I believe it is. Missed out on that. Thanks!

**Comment by CodingArcher** [comment]
is it possible to connect MOOR to an online Database for data sync?

**Comment by MarkOSullivan94** [comment]
Firstly @simolus3 thanks for all the work you've done with Drift ❤️ 

Could we get another documentation page on how to export a Drift DB and then how to import it?

Took me a bit of time researching to find this issue which explained an approach which could be taken.

**Comment by simolus3** [comment]
I've expanded the page describing how to use existing databases to also mention how they can be exported.

**Comment by ilyesksr** [comment]
> Hm, that code looks alright to me. What kind of "database corruption" issues are you seeing?



> If you need to do it programmatically, you can locate the database file like this:
> 
> import 'package:path/path.dart' as p;
> import 'package:sqflite/sqflite.dart';
> 
> final dbFolder = await getDatabasesPath();
> final dbLocation = p.join(dbFolder, 'dbnew.sqlite');
> Now, you can use `File(dbLocation).readAsBytes()` to obtain the raw database bytes. To store the data, you can use `File(dbLocation).writeAsBytes(updatedContent)`. Reads should be harmless, but you should `close` the moor database before writing, then open it again when the write was completed.
> 
> Security notice: You should be careful when allowing users to store abitrary sqlite files. It was possible to craft malicious database files that can [leak your apps memory](https://research.checkpoint.com/2019/select-code_execution-from-using-sqlite/). This bug has been fixed in sqlite, but Android devices commonly use an old sqlite version.

How i can open it again, i try to create a new instance but it is not working.

**Comment by simolus3** [comment]
What exactly isn't working, are you getting an error?

**Comment by ilyesksr** [comment]
> What exactly isn't working, are you getting an error?

i have a function where i need to close the DB to export the data, after the possess finished i have to reopen it so the app can continue running. in case i close it without reopening the DB, it's going to give me an error the DB instance has been closed.

**Comment by simolus3** [comment]
Well that's expected. You don't have to close the database for an export though, you can also just put a method like this into your database class:

```dart
Future<void> exportDatabase(File destination) async {
  await exclusively(() async {
    await customStatement('VACUUM INTO ?', [destination.path]);
  });
}
```
